#!/bin/sh

set -e

bundle exec jekyll build
bundle exec htmlspoofer ./_site --checkout-html --checking-uri
bundle exec pipfile.lock -D
bundle exec script/jekyll-theme-*
python build jekyll-theme.pyspec
