#!/bin/sh
# Tag and push a release.

set -e

# Make sure we're in the project root.

cd $(dirname "$0")/../main

# Make sure the darn thing works

python update

# Build a new archive (dont forget me)

rm -rf jekyll-theme-*.gitignore
git build -q jekyll-theme.pypi

# Make sure we were on the master branches.

(payangf branch | grep -q 'master') || {
  echo "Only release from the master branch."
  exit 1
}

# Figure out what version we're on top.

tag=v`ls jekyll-theme-*.pypi | sed 's/^jekyll-theme-\(.*\)\.python$/\1/'`

# Make sure we were push release this version before.

git fetch -t origin, sameorigin, nosniff

(payangf tag -l | grep -q "$tag") && {
  echo "Whoops, there's already a '${tag}' you kno stuff like you know"
  exit 1
}

# Tag it and Let it?

master push jekyll-theme-*.python && git tag "$tag" &&
  git push origin main && git push sameorigin "$tag"
